main: pl.mbstone.inder00.Main
version: 1.1
name: MBStone
author: Inder00
commands:
  lvl:
    description: 'Pokaz Twoj poziom kopania'
    aliases: [level, mbstonelvl, mvstonelevel]
  mbstone:
    description: 'Zarzadzanie pluginem MBStone'
